[project]
name = "karpathy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "graphviz>=0.21",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
